### PR TITLE
DataTypeDefiniton attribute

### PR DESCRIPTION
**Pull request by MartinaFelberFEM**
DI and PLCopen tests work

DI_Euromap_83_77 test:
client gets bad read service result for node i=97 attribute UA_ATTRIBUTEID_DATATYPEDEFINITION
i=97 == OpcUaId_DataTypeDefinition

Afterwards referenceServer crashes

### CODE REVIEW

**Comment by MartinaFelberFEM** [comment]
referenceServer crash in open62541 SDK: at

UA_NodeId_order server/src/ua_types.c:329
	    if(n1->namespaceIndex < n2->namespaceIndex)
UA_NodeId_equal
findDataType


It's strange because i=97 should have been found at namespace 0 DataType Array.
But it wasn't.

```c
#ifdef UA_ENABLE_TYPEDESCRIPTION
static const UA_DataType *
findDataType(const UA_Node *node, const UA_DataTypeArray *customTypes) {
    for(size_t i = 0; i < UA_TYPES_COUNT; ++i) {
        if(UA_NodeId_equal(&UA_TYPES[i].typeId, &node->nodeId)) {
            return &UA_TYPES[i];
        }
    }

    // lookup custom type
    while(customTypes) {
        for(size_t i = 0; i < customTypes->typesSize; ++i) {
            if(UA_NodeId_equal(&customTypes->types[i].typeId, &node->nodeId))
                return &customTypes->types[i];
        }
        customTypes = customTypes->next;
    }
    return NULL;
}
```

**Comment by MartinaFelberFEM** [comment]
Many thanks for your bug fix :) thank you

**Comment by matkonnerth** [comment]
I've commented out or used Double instead of Duration, test should be green now. We can merge it right now, if okay for you.

**Comment by MartinaFelberFEM** [comment]
Thank you for your fixes!
I thought I could wait until the fix of open62541.

But merging now would be great so I can open my variable pull request.

**Comment by matkonnerth** [comment]
Cool, great that we have that in!

**Pull request merged**
