### PR TITLE
WIP: Integration Client: print variable values

### PR DESCRIPTION
**Pull request by MartinaFelberFEM**
TODOs/open questsions:

- generated output files have an encoding error, something we print might be bad

- handle arrays -> Arrays are implemented but we haven't tested an ExtensionObject with array members, just ExtensionObject Arrays. We do not know how we can calculate the parse offset for arrayDimensionsSize and ArrayDimensions correctly, the information should be encoded in the data ...

- handle structs with optional fields

- handle unions

- some variables can't match, e.g. DateTime (BuildDate) or open server handles etc. ... How can we excluded them?

Tasks:
solve open issues, have a look through generated output, are there any nodeSetLoader errors? or just client issues ... ?

### CODE REVIEW

**Comment by MartinaFelberFEM** [comment]
Further client issues:

Namespace DI: FetchTransferResultData: InputArguments (ns=2;i=6532)
ArrayDimensions output is different, but UaExpert displays it correctly
So it's probably a client bug

**referenceServer output**
	Data = 
		{
			TransferID
			i=6
			-1
			**0**
			:
		}

**testServer output**
	Data = 
		{
			TransferID
			i=6
			-1
			**1**
			:
		}


**referenceServer**
image


**testServer**
image

**Comment by MartinaFelberFEM** [comment]
ns=2;i=15007 : StaticNumericNodeIdRange
-> Namespace Information

image


**referenceServer:**
```
Value = {
	DataType info:
		Id = i=12
		Name = String
		Encoding Id = 0
		Index = 11
		Kind = 11
		Pointer free = 0
		Overlayable = 0
		MemSize = 16
		MembersSize = 0
		Members: = 
	Storage Type = 0
	ArrayDimensions = []
	Array Length = 1
	Data = 
		1:65535
}
ValueRank = 1
ArrayDimensions = [	0,]
```

image


VS testServer:
```
Value = {
	Empty
}
```
image

**Comment by MartinaFelberFEM** [comment]
ns=2;i=15008 StaticStringNodeIdPattern

referenceServer
Value contains 1 newline
image


testServer
Value contains 2 newlines ...
image

**Comment by MartinaFelberFEM** [comment]
ns=2;i=6450: EnumStrings

**referenceServer**
	Data = 
		:NORMAL
		:FAILURE
		:CHECK_FUNCTION
		:OFF_SPEC
		:MAINTENANCE_REQUIRED

image



**testServer:**
	Data = 
		
          :NORMAL
		
          :FAILURE
		
          :CHECK_FUNCTION
		
          :OFF_SPEC
		
          :MAINTENANCE_REQUIRED


image

**Comment by MartinaFelberFEM** [comment]
Client error at ExtensionObject - DataType Argument - ArrayDimensions:

i=14480
ValueRank == 1 -> ArrayDimensions are garbage
		{
			FieldNameAliases
			i=12
			1
			**161895856**
			:
		}

**Comment by matkonnerth** [comment]
This should fix the issue with the numeric range https://github.com/matkonnerth/nodesetLoader/pull/121

**Comment by matkonnerth** [comment]
whitespace issues should be fixed with https://github.com/matkonnerth/nodesetLoader/pull/122

**Comment by matkonnerth** [comment]
I will merge this back when the tests are green. 
use UA_Print for print values
added value_utils_mock because of this issues
- values with timestamps cannot be compared -> test always fails
- open62541 automatically initializes variable with values, if the nodeset doesn't define one, the nodesetLoader not

I will open a separate issue for the last one

**Pull request merged**
